### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by esuah** [redcode/Z80#4]
Hi, i port your code and i have a question about the case 0:
There is the ROL(value) and after that carry flag evaluation.
In cases 1-7 there is first the carry flag evaluation and after that the operation.
Is that a typo or is it the expected behavior?

(starting at about line 540 in Z80.c)
	switch ((DATA[offset] >> 3) & 7)
		{
		/* rlc		 .----------------.
			.----.	 |  .---------.   |
			| CF |<-----| 7 <-- 0 |<--'
			'----'	    '--------*/
		case 0:
		ROL(value);
		cf = value & 1;
		break;

		/* rrc	.----------------.
			|   .---------.  |   .----.
			'-->| 7 --> 0 |----->| CF |
			    '---------'      '---*/
		case 1:
		cf = value & 1;
		ROR(value);
		break;

		/* rl	.-------------------------.
			|  .----.   .---------.   |
			'--| CF |<--| 7 <-- 0 |<--'
			   '----'   '--------*/
		case 2:
		cf = value >> 7;
		value = (zuint8)((value << 1) | F_C);
		break;

		/* rr	.-------------------------.
			|   .---------.   .----.  |
			'-->| 7 --> 0 |-->| CF |--'
			    '---------'   '---*/
		case 3:
		cf = value & 1;
		value = (zuint8)((value >> 1) | ((zuint8)F_C << 7));
		break;

		/* sla	.----.	 .---------.
			| CF |<--| 7 <-- 0 |<-- 0
			'----'	 '--------*/
		case 4:
		cf = value >> 7;
		value <<= 1;
		break;

		/* sra	    .---------.   .----.
			.-->| 7 --> 0 |-->| CF |
			|   '---------'   '----'
			|     |
			'----*/
		case 5:
		cf = value & 1;
		value = (zuint8)((value & 128) | (value >> 1));
		break;

		/* sll	.----.	 .---------.
			| CF |<--| 7 <-- 0 |<-- 1
			'----'	 '--------*/
		case 6:
		cf = value >> 7;
		value = (zuint8)((value << 1) | 1);
		break;

		/* srl	     .---------.   .----.
			0 -->| 7 --> 0 |-->| CF |
			     '---------'   '---*/
		case 7:
		cf = value & 1;
		value >>= 1;
		break;

		/* Uncoment to avoid compiler warnings */
		/*default: cf = 0;*/
		}

**Comment by Agaxia** [comment]
Hello,

You are right. It was a bug. Surprisingly, none of the test suites detected it. I've fixed it: https://github.com/redcode/Z80/commit/646e72f3b73034235bec168c135abc066df8e9df

Thanks for reporting!

**Comment by esuah** [comment]
Isn't the fix does the same? first rol and then evaluate cf?

**Comment by Agaxia** [comment]
Sorry, I understood incorrectly. The fix that I've applied doesn't modify the behavior. The implementation was right. Now the code is a little more optimized.

The code was right, the value is rotated **BEFORE** because the bit 7 of the **input/initial** value is copied to CF, which is explained in page 214 of the [Z80 CPU User Manual](https://zxe.io/depot/documents/Z80%20CPU%20User%20Manual%20rev11%20%282016-09%29%28Zilog%29%28%23UM008011-0816%29%28en%29%5B%21%5D.pdf).

After the rotation, what previously was the bit 7, is now the bit 0, which is then copied to CF.

![image](https://user-images.githubusercontent.com/30360601/187047539-47530fd4-9a7e-475a-88f0-dd08d21e2511.png)

If you try rotating the value after copying the bit 0 to CF, you will see that many test suites fail.

Sorry about my previous answer. I hope everything is crear now. The code was and is OK.

**Comment by esuah** [comment]
Thank you!
